### ISSUE TITLE
Honeybadger blocking Fingerprint Pro requests (Vue 3)

### ISSUE THREAD

**Issue by developerdino** [honeybadger-io/honeybadger-js#1058]
## What are the steps to reproduce this issue?
1. git clone https://github.com/verifiedit/fp-hb-integration-issue.git
2. set env as per readme instructions.
3. enable Honeybadger with `VITE_ENABLE_HONEYBADGER=true`

## What happens?
Fingerprint Pro is blocked making request.

## What were you expecting to happen?
I should be able to get a fingerprint.

## Any logs, error output, etc?
Unfortunately none, the only thing I see is when I turn Honeybadger off, I'm able to get the Fingerprint request to go through.

## Any other comments?
I've created a minimal app to show the behaviour which I've been able to replicate on each request.

I've deployed the same app twice, once with Honeybadger enabled and once disabled.
- Honeybadger enabled: https://fingerprint-honeybadger.verifiedit.dev/
- Honeybadger disabled: https://fingerprint-only.verifiedit.dev/

Both are running the exact same code as per https://github.com/verifiedit/fp-hb-integration-issue repo.

## What versions are you using?
**Operating System:** MacOS/iOS
**Package Name:** @honeybadger-io/vue
**Package Version:** 5.3.0
**Browser Version:** 112.0.5615.137 (Official Build) (arm64)/Safari on iOS Version 16.4.1

#### Fingerprint Pro
**Package Name:** @fingerprintjs/fingerprintjs-pro-vue-v3
**Package Version:** 1.1.3

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lxdk1)

**Comment by BethanyBerkowitz** [comment]
Thank you for sending this example! I've tested it out and I see the same problem you're seeing (I'm using Chrome on Mac). Not yet sure what's causing it, but we're looking into it.

**Comment by LucasBradley01** [comment]
Hello, I am technical support from Fingerprint. The issue is only with our JS Agent 3.8.11, so we rolled back to 3.8.10. The problem is with overrides to the open, send, and setRequestHeader method on XMLHttpRequest prototype from other code like Honeybadger. Our 3.8.11 agent ended up calling those overrides, and that ended up causing the network request error.

We will make sure the agent is not vulnerable to these overrides when we re-release it. Everything is working now, even the given sample page: https://fingerprint-honeybadger.verifiedit.dev/ since we distribute agent through CDN. This issue can be closed.

**Comment by dj-stormtrooper** [comment]
@BethanyBerkowitz Also worth to mention that: 

In a recent Fingerprint update client starts to pass to `xhr.open` URL with type [URL object](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) instead of type `string` and it led to issue here (it works same way as in fetch - function accepts both types)

We will fix this behaviour in the next release back to `string` type, but I think you may fix it on Honeybadger side as well, because it may be a common thing

**Details**
It fails in parsing URL, because URL object doesn't have `match` method (url with type string is expected in this function)
https://github.com/honeybadger-io/honeybadger-js/blob/a39a9e94505e9869601a1f253a5a9d7d9a8ab729/packages/js/src/browser/util.ts#L90

Parsing function is used here https://github.com/honeybadger-io/honeybadger-js/blob/a39a9e94505e9869601a1f253a5a9d7d9a8ab729/packages/js/src/browser/integrations/breadcrumbs.ts#L112

I can make a PR with a fix to this repo

**Comment by BethanyBerkowitz** [comment]
@dj-stormtrooper Thanks for this info, we'd be happy to see your PR! I'll close this issue in the meanwhile.

**Comment by developerdino** [comment]
Thanks @LucasBradley01 and @BethanyBerkowitz for helping sort this issue out so quickly.
