### ISSUE TITLE
Breadcrumbs messing with fetch error handling

### ISSUE THREAD

**Issue by kgunbin** [honeybadger-io/honeybadger-js#1158]
## What are the steps to reproduce this issue?
In the browser console, run the code with HB installed:
```javascript
try {
  response = await fetch('https://httpbin.org/status/429');
} catch (error) {
  console.log('There was an error', error);
}
```

## What happens?
With HB enabled, got the error but no message:
```
breadcrumbs.js:203     GET https://httpbin.org/status/429 429
(anonymous) @ breadcrumbs.js:203
(anonymous) @ VM984:2
Response {type: 'cors', url: 'https://httpbin.org/status/429', redirected: false, status: 429, ok: false, …}
```

Run the same code without HB:
got the error and the message
```
VM43:2     GET https://httpbin.org/status/429 net::ERR_FAILED
(anonymous) @ VM43:2
VM43:4 There was an error TypeError: Failed to fetch
    at <anonymous>:2:20
```

## What were you expecting to happen?

I expect error handler in the `catch` clause to still be invoked

## What versions are you using?
**Operating System:** MacOs Ventura
**Package Name:** @honeybadger-io/js
**Package Version:** 6.0.3
**Browser Version:** Chrome 115

**Comment by subzero10** [comment]
Hey @kgunbin, thanks for submitting an issue!

You said that when you run the code without HB, the catch block is executed. 
Can you please log the HTTP status code and double-check that indeed it's a `429` when the catch block is executed? The reason I'm asking is because `4xx` status codes are not supposed to throw, as per the [Fetch API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful). When I tried it your example a few times, I was only able to have the catch block executed when the status code was 504 (I couldn't reproduce more than once;  I guess it was a random error).

As per the HB integration, you can see [here](https://github.com/honeybadger-io/honeybadger-js/blob/97dceff46909215d894e9e30bdc2d93160da0c1b/packages/js/src/browser/integrations/breadcrumbs.ts#L237C28-L237C28) that when the catch block is executed, the error is re-thrown, so it should eventually reach your catch block. In your case, 4xx errors are not thrown.

**Comment by kgunbin** [comment]
@subzero10 You're right, my bad calling the non-existing URL 🤦 
Sorry

**Comment by subzero10** [comment]
No worries! I'm glad we sorted it out! Thank you for using Honeybadger!
