### ISSUE TITLE
The native module not found in typescript expo react native

### ISSUE THREAD

**Issue by petermunachi** [honeybadger-io/honeybadger-js#1226]
I see this error when I try to use honeybadger in my typescript expo app ```ERROR  [Honeybadger] The native module was not found. Please review the installation instructions.```

## What are the steps to reproduce this issue?
1. … npm install "@honeybadger-io/react-native"

2. …Add this configuration code on App.jsx
```    
Honeybadger.configure({
      apiKey: '', 
      revision: "testRevisionExpo123",
      debug: true,
      reportData: true, // report data even in dev environment
    })
   ```
3. … Run npm run android

## What happens?
…I get this error on the console and on the App in the Emulator
`````ERROR  [Honeybadger] The native module was not found. Please review the installation instructions.`````

## What were you expecting to happen?
…

## Any logs, error output, etc?
…
`````ERROR  [Honeybadger] The native module was not found. Please review the installation instructions.`````

## Any other comments?
…

## What versions are you using?
**Operating System:** … Windows 11 OS
**Package Name:** … @honeybadger-io/react-native
**Package Version:** … "@honeybadger-io/react-native": "^6.2.2"
**Browser Version:** …

**Comment by BethanyBerkowitz** [comment]
Hi @petermunachi, thanks for reaching out! The Honeybadger react-native package uses custom native code so that we can catch errors that happen in native-land and not just the javascript errors. Expo Go doesn't deal with custom native code by default. This means that `expo start --android` won't work correctly, and you probably need to use `npx expo run:android`.

Here's the documentation that I think is relevant here: https://docs.expo.dev/workflow/customizing/. Please check it out and let us know if this helps!

**Comment by BethanyBerkowitz** [comment]
Hi @petermunachi, since we haven't heard back I'm going to assume that the fix above worked for you. If it didn't, please re-open the issue!
