### ISSUE TITLE
typescript.js included in esbuild output through cosmiconfig

### ISSUE THREAD

**Issue by juarezjaramillo** [honeybadger-io/honeybadger-js#1264]
## What are the steps to reproduce this issue?
1. Install @honeybadger-io/js v6.7.1 on a serverless framework project
2. Package serverless project using esbuild (`serverless package`)

## What happens?
3. "typescript.js"  is included in the output js making the generated files huge.

## What were you expecting to happen?
typescript.js not included in the generated js

## Any logs, error output, etc?
Parts of the generated file:
```
// node_modules/typescript/lib/typescript.js
var require_typescript = __commonJS({
  "node_modules/typescript/lib/typescript.js"(exports, module) {
    "use strict";
    var ts = (() => {
....
.... lots of content in here
....

// node_modules/cosmiconfig/dist/loaders.js
var require_loaders = __commonJS({
  "node_modules/cosmiconfig/dist/loaders.js"(exports) {
    "use strict";
...
    var typescript;
    var loadTsSync = function loadTsSync2(filepath, content) {
      if (typescript === void 0) {
        typescript = require_typescript();
      }
      const compiledFilepath = `${filepath.slice(0, -2)}cjs`;
      try { ...
```

## Any other comments?
typescript.js appears to be included through cosmiconfig dependency. (Can cosmiconfig be marked as optional?)
It's solved by using @honeybadger-io/js 6.5.3 since cosmiconfig wasn't a dependency at that version.

## What versions are you using?
**Operating System:** Mac M1 Pro with Sonoma 14.1.2
**Package Name:** @honeybadger-io/js
**Package Version:** 6.7.1
**Browser Version:** N/A

**Comment by OlegLustenko** [comment]
Hey! I think it's pretty much related to this issue.

Whenever we are running the server we are getting a lot of this

![image](https://github.com/honeybadger-io/honeybadger-js/assets/11524061/1ad5a374-7526-476b-8073-0bb6dc67b7a3)

**Comment by subzero10** [comment]
Hello @juarezjaramillo, thanks for reporting this!

I can see why "typescript" is installed:
- the "typescript" package is an optional dependency of _cosmiconfig_
- the default behavior of _npm_ is to install optional deps.

You could work around this by trying `npm install --omit=optional`.
However, this is not ideal and we are exploring alternatives such as [shrinkwrap](https://docs.npmjs.com/cli/v10/commands/npm-shrinkwrap) or manually writing a module to load configuration files, without _cosmiconfig_.

Moving on to the next issue you are facing: _Critical dependency: the request of a dependency is an expression_
I can't reproduce it, but I see how it's related to cosmiconfig. With a quick google search, I'd assume you are getting this because of how the app is being packaged/built. I am still diving into it and will write updates here when I have something more to share.

**Comment by subzero10** [comment]
Hello @juarezjaramillo, this should be fixed with `v6.7.2`. We removed the `cosmiconfig` dependency.

**Comment by OlegLustenko** [comment]
@subzero10 After upgrading to latest version, we started to getting this one

![image](https://github.com/honeybadger-io/honeybadger-js/assets/11524061/b3929cea-ec98-453c-9acf-2a7766396aa4)

can it be somehow related?

(adding this message here for reference, going to create a new issue if there is not yet created one)

**Comment by subzero10** [comment]
Hey @OlegLustenko, I doubt it's related, but I found the issue and submitted a [PR](https://github.com/honeybadger-io/honeybadger-js/pull/1276) for the fix. We'll get a patch version released asap (probably today)!

**Comment by subzero10** [comment]
@OlegLustenko, please try [@honeybadger-io/js@6.8.1](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io%2Fjs%406.8.1)!
