### ISSUE TITLE
Chrome SameSite cookie attribute warning

### ISSUE THREAD

**Issue by ufchrisg** [honeybadger-io/honeybadger-js#230]
## What are the steps to reproduce this issue?
1. Go to a site using honeybadger-js with the console open

## What happens?
The following warning appears in console:
```
A cookie associated with a cross-site resource at https://app.honeybadger.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

## What were you expecting to happen?
No warning

## Any logs, error output, etc?
Warning provided above.

## Any other comments?
We get two of these, one for `https://app.honeybadger.io/` and one for `http://app.honeybadger.io/`

## What versions are you using?
**Operating System:** macOS Mojave 10.14.6
**Package Version:** honeybadger-js v2.0
**Browser Version:** 77.0.3865.120 (Official Build) (64-bit)

**Comment by joshuap** [comment]
I haven't been able to reproduce this one. It may have been an issue app.honeybadger.io which has since been fixed. We don't set any cookies in honeybadger.js, so I'm not sure how this library could be causing it. If you're still getting this warning, could you let me know at support@honeybadger.io? It would be helpful to know the name of the cookie which is causing the problem, which you can find under Application>Storage>Cookies as mentioned in the console warning (screenshots are always helpful). Thanks!
