### ISSUE TITLE
Return a promise from Honeybadger.notify

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#327]
We now support this:

```javascript
Honeybadger.notify('testing', {
  afterNotify: (err, notice) => console.log(err, notice)
});
```

Could we return a promise, so it could look like this?

```javascript
Honeybadger.notify('testing').then(notice => {
  console.log(notice);
}).catch(error => {
  console.log(error);
});
```

**Comment by ParamagicDev** [comment]
@joshuap I hacked around and have a rough idea of how this would look. I have it on this branch here: https://github.com/honeybadger-io/honeybadger-js/tree/feat/return-a-promise-from-notify

There are a couple problems with trying to overload `notify` to handle both cases, first: this function returns booleans and users could potentially be using those booleans to determine various paths IE: 

```js
const notifyBool = Honeybadger.notify("testing")
if (notifyBool) {
  doX()
} else {
  doY()
}
```

The other issue is that any node based user will now have to catch any errors or they will get an `unhandledPromiseException` for not `catching` errors.

Perhaps instead of trying to make notify work like a promise (its hard because it doesnt use the traditional callback path, it uses a hook based approach) maybe we could split notify between the following:

```js
Honeybadger.notify('testing', {
  afterNotify: (err, notice) => console.log(err, notice)
});

Honeybadger.notifyAsync("testing").then((notice) => { console.log(notice) }).catch((err) => console.log(err))
``` 

This would allow both implementations coexist. Obviously extracting out the behavior of `Honeybadger.notify()` into reusable chunks will be key as well. Let me know how youd like to move forward on this!

**Comment by joshuap** [comment]
@ParamagicDev thanks for the research, this is helpful! I'll think about this one a bit more. In the meantime let's continue on other issues. 👍

**Comment by subzero10** [comment]
Hey @joshuap, I think we have to re-visit the idea of having an async version of `notify`, see #682.

**Comment by subzero10** [comment]
This has been released with v4 (currently in beta).
