### ISSUE TITLE
What is the best practice for reporting application-generated JS errors?

### ISSUE THREAD

**Issue by zinkkrysty** [honeybadger-io/honeybadger-js#33]
I have enabled honeybadger-js errors with `onerror: true`, and I am getting a lot of errors some of which come from external libraries and other script files loaded in the client browser. Is there any best practice for wrapping one's own code with `try catch notify` other than doing it for every piece of code that "might break"?

How are other people doing this, can we see some examples?

**Comment by joshuap** [comment]
You currently have these options:

1. Use any error handling hooks your framework provides (although this might not catch *all* errors in your application code).
2. Use try/catch.
3. Alternatively, we provide a `Honeybadger.wrap` function which makes the try/catch approach a bit easier. More on that [here](http://docs.honeybadger.io/article/199-catching-javascript-errors-in-callbacks).
4. If you're using jQuery I have a [beta plugin](http://js.honeybadger.io/honeybadger-jquery.js) which automatically reports any errors which happen in asynchronous ajax requests as well as event callbacks.

We will probably be taking a similar approach to #4 in the future in order to do more wrapping of core JavaScript features (so that we can report more automatically). I don't have any examples of how other users use try/catch, but any general approaches to error handling in JavaScript you can find online should work for Honeybadger.

**Comment by zinkkrysty** [comment]
Thanks for writing down the options. It's useful to know them. 

However, in a traditional Rails app, if you have a lot of files included with the `//= require filename` directive, I don't know exactly how the wrap will be used, as Sprockets (the asset pipeline) doesn't allow the require directives to be wrapped with other code, so the only option will be to wrap the code within every single file with the try/catch or the Honeybadger.wrap function, which requires a lot of changes. 

I'll try the jQuery plugin, though it only works for code within jQuery wrappers, the rest of the errors in the application will remain untracked.

I'm thinking if it's possible to use the `onerror` event but only filter important errors comming from the code of my application. Do you have experience doing this?

**Comment by zinkkrysty** [comment]
I updated the [honeybadger-jquery.js](https://gist.github.com/zinkkrysty/14bccc4466a3f1f6d2f0) file (with better checks) in case anyone needs it.
