### ISSUE TITLE
Hide the api key in the browser

### ISSUE THREAD

**Issue by edzhelyov** [honeybadger-io/honeybadger-js#358]
This is not an issue, but a question, but И couldn't find where to ask it, so I'm putting it here.

I'm integrating honeybadger in the browser and we rely on a meta tag in the head. But it's very obvious and it can be hijacked and abused. In a way, do you have some recommendations on how to supply the API key in a more secure way in the browser?

**Comment by joshuap** [comment]
@edzhelyov unfortunately there's no way to hide the API key in the browser, since it needs to be sent with error reports. Project API keys are write-only--worst case scenario is that a bad actor could create additional error reports in your account (which we could then delete). I've never heard of that happening. You can also rotate your project API key at any time under Project Settings, which will instantly invalidate the old key. Hope that helps!

**Comment by edzhelyov** [comment]
Thanks for the quick response, appreciate it.
