### ISSUE TITLE
`require` oddities with bower and sprockets 3

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#37]
Not entirely sure if this is an issue with `honeybadger-js` or elsewhere. We're using the bower package through `rails-assets` and when we tried to upgrade `sprockets` to version 3 we got an odd error:

```
Sprockets::FileNotFound: couldn't find file 'honeybadger.js' with type 'application/javascript'
```

We took a peek in the gem generated by `rails-assets` and it turns out there's a `honeybadger.js.js` file with a second `.js` on the end, and changing our require line to:

```js
//= require honeybadger.js.js
```

fixed the problem for us.

**Comment by joshuap** [comment]
@mockdeep thanks, I'll look into this and figure out why bower is messed up. I seem to remember some weirdness there in the past.

**Comment by joshuap** [comment]
I think I see what's happening. We've named our bower package "honeybadger-js". Apparently rails-assets creates the root asset file based on the package name, not on the main src file. It also seems to be converting the `-` in the name to a `.` and then appending `.js`, so you get `honeybadger.js.js`.

I see two solutions:

1. Update our docs to say to use `honeybadger.js.js` when using rails-assets. This naming is counter-intuitive, though.
2. Change the name of our bower package to "honeybadger" instead of "honeybadger-js". This would create two packages on bower and rails-assets, which could also be potentially confusing (although maybe we could ask them to hide one). Of course, our docs would be updated with the correct package.

Any thoughts on which is more intuitive to you? :)

**Comment by mockdeep** [comment]
Hmm, well the first feels kind of odd, so I guess I'd vote on the second. Maybe deploy a version to `honeybadger-js` that points people at the new version. I was going to suggest maybe opening an issue on rails assets, but it looks like [they don't have a bright future](https://github.com/rails-assets/rails-assets/issues/291). We just set up `browserify-rails`, so we'll probably be moving things over to npm soon anyway.

**Comment by joshuap** [comment]
As of v0.4.0 the bower package has been renamed to "honeybadger", so now you can do:

```ruby
gem 'rails-assets-honeybadger'
```

```js
//= require honeybadger
```

v0.3.x and earlier should still continue to function normally, but you may need to change local references to "bower_components/honeybadger-js" to "bower_components/honeybadger" when upgrading to v0.4.0.

**Comment by mockdeep** [comment]
Great, thanks!
