### ISSUE TITLE
Resize handler performance

### ISSUE THREAD

**Issue by MartinMalinda** [honeybadger-io/honeybadger-js#490]
<img width="881" alt="Screenshot 2020-11-28 at 21 23 09" src="https://user-images.githubusercontent.com/9468793/100525312-fee70680-31bf-11eb-8975-9ce8b3f54dcb.png">

I'm wondering what heavy logic is there for error reporting tool to do on window resize. Is this to be expected?

**Comment by MartinMalinda** [comment]
Upon closer inspection it seems like it's not the honeybadger itself that is the culprit, honeybadger is merely reporting this violation. Is that correct?

Thanks!

**Comment by joshuap** [comment]
@MartinMalinda that's correct—that looks like a console log message; we instrument `console.log` (so that we can record breadcrumbs), which is why it shows honeybadger.min.js as the location. Unfortunately, there's no way to see the original location of the log message when this feature is turned on, but you can disable `console` instrumentation with this config:

```js
Honeybadger.configure({
  breadcrumbsEnabled: {
    dom: true,
    network: true,
    navigation: true,
    console: false
  }
})
```

https://docs.honeybadger.io/lib/javascript/guides/breadcrumbs.html
