### ISSUE TITLE
Sourcemaps do not seem to be supported

### ISSUE THREAD

**Issue by abepetrillo** [honeybadger-io/honeybadger-js#61]
We have added the devtool option of `sourcemaps` as [suggested](https://github.com/honeybadger-io/honeybadger-js#sourcemaps). I've also checked that the file downloaded by the browser includes the sourcemap URL reference:

`//# sourceMappingURL=bundle-0505d8603c675bbace9b.js.map`

This file is available directly from the website, and honeybadger still cannot provide a stacktrace or decent line number for where the exception was raised. Are there any known issues with this feature?

**Comment by joshuap** [comment]
Currently it may take a minute or two for the source map to be applied to new errors. That's because we send alerts immediately, before trying to download the source map. Also, source maps are applied only to *new* errors, so if you had the same error before you uploaded your source map then you would need to delete the error for the source map to be applied the next time the error occurs. I'm actually in the middle of an update to the source maps feature which will add some new features and make it much more reliable.

If you're still having issues with source maps in the meantime, could you email support@honeybadger.io with details about the error that isn't showing the correct stack trace? I can help more there!

**Comment by abepetrillo** [comment]
Sure will email. The code was up for a while (1 hour?) and the source maps would have been uploaded at the same time.

So for client side errors, should be just delete all JS errors with each new deployment? Is there a way of doing this through an API? Again will email support thanks for the help.
