### ISSUE TITLE
Error thrown when using with Honeybadger React Native

### ISSUE THREAD

**Issue by andreybutov** [honeybadger-io/honeybadger-js#627]
While integrating this package to work with Honeybadger React Native ( https://github.com/honeybadger-io/honeybadger-react-native/issues/3#issue-870133998 )

... an exception was thrown:

**TypeError: undefined is not an object** 

This happened while evaluating ```window.location.protocol``` in the constructor in **src/browser.ts**

**Comment by joshuap** [comment]
@andreybutov I'm thinking we probably want to create a separate client rather than try to support native in the browser integration. Do you know if RN can support any of [these browser integrations](https://github.com/honeybadger-io/honeybadger-js/tree/master/src/browser/integrations)? I'm not sure how it works.

**Comment by andreybutov** [comment]
@joshuap I think our earlier idea of perhaps relying on the universal core is the most promising one for now. I'm going to explore that. At worst, HB RN will need to implement a few pieces that are missing from core, rather than modifying universal to accommodate HB RN.
