### ISSUE TITLE
Honeybadger Error Reporting `UnhandledPromiseRejectionWarning: Unspecified reason`

### ISSUE THREAD

**Issue by grantkee** [honeybadger-io/honeybadger-js#645]
## What are the steps to reproduce this issue?
1. Setup honeybadger on my app. Confirm things work as expected.
2. Get a notification for honeybadger error from honeybadger source code
     > Error in script: `https://js.honeybadger.io/src/browser/integrations/onunhandledrejection.ts:47:18:in `'unknown'
3. Not sure how to reproduce from my user's side

## What happens?
I get the following error:
<img width="1440" alt="Screen Shot 2021-10-13 at 1 22 57 PM" src="https://user-images.githubusercontent.com/49913008/137191623-e88aafbb-3467-41da-9cdd-5259dd813e3a.png">

## What were you expecting to happen?
I expected the report to help me identify an error in my code, but it seems to be reporting an error from honeybadger code.

## Any logs, error output, etc?
Attached here: [report_data.gz](https://github.com/honeybadger-io/honeybadger-js/files/7340508/report_data.gz)(exported from honeybadger app)
- message: UnhandledPromiseRejectionWarning: Unspecified reason
- backtrace: onunhandledrejection.ts  47  18  unknown(...) | https://js.honeybadger.io/src/browser/integrations/onunhandledrejection.ts:47:18:in 'unknown'

## Any other comments?
The user involved with causing this error is a teacher accessing content from a school district's computer, probably behind a firewall and running who knows what other type of "protective" software. The error has happened 506 times in the last 90 minutes.

It's entirely possible that I have an error in my code that's ultimately responsible for causing this. I'm just not sure how to find that from the report itself.

#### From the honeybadger report:
**Operating System:** Mac OS X 10.15.7
**Package Version:** JS 3.2.5
**Browser Version:** Chrome v94.0.4606.71

User Agent from report: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

**Comment by joshuap** [comment]
Hi @grantkee.

This error is showing the Honeybadger integration as the source of the notification because there is no stack trace associated with the error. When there is no error stack trace, we create a stack trace that points to the location where `Honeybadger.notify` was called, which was internal in this case. 

"UnhandledPromiseRejectionWarning: Unspecified reason" usually means that a [JavaScript promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) was rejected without an argument (rejections should normally include a string error message, and error object, etc).

Unfortunately, there's not much we can do to improve notifications like this, because there is just not enough data available. If you don't want these notifications specifically, you could ignore them—see [Reducing Noise](https://docs.honeybadger.io/lib/javascript/guides/reducing-noise/). You can also [disable `enableUnhandledRejection` entirely](https://docs.honeybadger.io/lib/javascript/reference/configuration/#configuration-options).

Thanks!
