### ISSUE TITLE
Array is Converted to JSON Object in Honeybadger.notify

### ISSUE THREAD

**Issue by manchunlam** [honeybadger-io/honeybadger-js#67]
When using `Honeybadger.notify` in the following situation

```
var foo = {
  bar: {
    hello: [
      { id: 5, name: 'five' },
      { id: 6, name: 'six' }
    ]
  }
}

var err = new Error();

Honebadger.notify(err, { context: foo })
```

The _Context_ as shown in `honeybadger.io/projects/*/faults/*` is

```
{
  "bar": {
    "hello": {
      "0": {
        "id": "5",
        "name": "five"
      },
      "1": {
        "id": "6",
        "name": "six"
      }
    }
  }
}
```

Notice how `bar.hello` is no longer an array.

Could you please take a look?

Thank you.

**Comment by joshuap** [comment]
@manchunlam thanks, looks like a bug. I'll look into it.

**Comment by joshuap** [comment]
I looked into this and unfortunately it's not something I can change at this time. Our current transport method uses a query string to send the error data to our servers, and that requires that I include the index of array items. A side effect is that those items are displayed as objects since there's no way to tell the difference (although they are also technically objects in JavaScript and should behave in similar ways).

#51 may be a way to correct this behavior since we'd be able to send the payload as JSON.

Sorry about that, @manchunlam. Let me know if you have any thoughts.
