### ISSUE TITLE
`Configure` not found in '@honeybadger-io/js'

### ISSUE THREAD

**Issue by p8** [honeybadger-io/honeybadger-js#864]
## What are the steps to reproduce this issue?

After upgrading to version 4.x the following code no longer works with Webpacker.
```
// Copied from https://docs.honeybadger.io/lib/javascript/integration/stimulus/
import * as Honeybadger from '@honeybadger-io/js'

Honeybadger.configure({
  apiKey: 'Your Honeybadger API key',
  environment: 'production',
  revision: 'git SHA/project version'
})
```

## What happens?
I get the following error:
```
Failed to compile.

./app/javascript/packs/application.js 29:0-21
"export 'configure' (imported as 'Honeybadger') was not found in '@honeybadger-io/js'
```

## What versions are you using?
**Webpacker:** 5.4.3
**Package Version:** Tested 4.0.5 and 4.1.1

**Comment by subzero10** [comment]
Hello @p8, can you try importing like below and let me know if it works for you?
```
import Honeybadger from '@honeybadger-io/js'
```

**Comment by p8** [comment]
Hi @subzero10 then I get:
`export 'default' (imported as 'Honeybadger') was not found in '@honeybadger-io/js'`

**Comment by subzero10** [comment]
The difference between v3 and v4 of the Honeybadger client is that on v3 the typescript compiler transpiles to es5 and v4 transpiles to es6. There are some more details in this process, because this is the time we moved to the monorepo but after a few hours of testing, I believe this is what broke compatibility with Webpacker.

I was able to reproduce this issue as @p8 mentioned above with Webpacker. I'm not very familiar with Webpacker but what I know is that it is a webpack wrapper written in Ruby. My guess is that some configuration that comes from webpacker is causing the problem. I say that because I was able to include `@honeybadger-io/js@4.1.2` in a simple webpack project and it worked. There is also an example project [here](https://github.com/honeybadger-io/honeybadger-js/tree/master/packages/js/examples/webpack). I tried `@honeybadger-io/js@4.1.2` with webpack v4 and webpack v5. Everything works OK with the default configuration.

While debugging, I came to realize that we should probably improve the way we export the javascript honeybadger client. For example, we use rollup to provide different bundles of the client. 
For the browser client, it makes sense to have a bundle.
But what about the nodejs client? Should it be bundled?
What about this case, where the client is to be consumed by a bundler? Ideally the bundler should take the source code (or the transpiled ts code) and decide how to bundle it, right?
In fact, I realized I have to do some more studying on publishing npm modules for different frameworks and platforms.

What do you think @joshuap @shalvah ?

For now, I created a [PR](https://github.com/honeybadger-io/honeybadger-js/pull/866) that reverts to es5, which should solve this problem. I think we have to further discuss on how to improve the way we export the module and create ticket(s).

**Comment by joshuap** [comment]
@subzero10 For the npm package entrypoints (the `main` and `browser` entries in package.json), each build should be using the least amount of bundling/transpiling possible. If I recall correctly, the main reason I used rollup for all builds is for TypeScript support (although there may be other reasons), and rollup made it easier to output several builds for different environments (including the full CDN bundle). If we can reduce the amount of bundling, I'm interested.

**Comment by subzero10** [comment]
@joshuap Thanks for the insights, I will do some research and come back with suggestions. FYI, for typescript compilation, we are using the `tsc` compiler directly now because of we make use of [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html), a feature that is not supported with the typescript plugin of rollup. Rollup only does the bundling since we switched to the monorepo.

@p8 Can you please give this a try with `v4.1.3`? Thanks!

**Comment by p8** [comment]
Thanks @subzero10 It was working now!
