### ISSUE TITLE
Package size increased considerably

### ISSUE THREAD

**Issue by bpinto** [honeybadger-io/honeybadger-js#915]
## What are the steps to reproduce this issue?
Open [bundlephobia](https://bundlephobia.com/package/@honeybadger-io/js@4.6.0) and check the bundle size graph.

## What happens?

The size of the package has increased considerably in the last few minor versions even though not much code has been added.

## What were you expecting to happen?

Bundle size to have slightly increased.

## Any logs, error output, etc?

No.

## Any other comments?

No.

## What versions are you using?

Irrelevant.

**Comment by subzero10** [comment]
Hey @bpinto, thanks for submitting an issue!

I can see 3 bumps regarding size:
- `v3.2.9` -> `v4.0.0` -> This was a big release (features/fixes). I compared the bundled files and it appears that the bump is due to the amount of code added. Add to the fact we have an isomorphic package with both browser and server distributions, any changes will end up in two generated bundles.
- `v4.0.5` -> `v4.1.0` -> Another big release, but a different kind. We moved to a monorepo for all our javascript packages. With this release, some code from the `js` package was extracted to a different `core` package, so I'm surprised to see that the zipped or minified file is actually bigger. However, it may be due to the fact that we now have more typescript `.d.ts` files generated because we changed the way we build typescript in the projects (we used to use rollup, but now we use the tsc compiler directly to benefit from [Typescript Project References](https://www.typescriptlang.org/docs/handbook/project-references.html)).
- `v4.1.2 -> v4.1.3` -> This is most probably due to [this](https://github.com/honeybadger-io/honeybadger-js/pull/866). With v4, we transpiled to es6 which caused some issues for some people.

All in all, I think the change in package size is acceptable, considering all the changes we introduced. At the time of making these changes we did not consider looking at the package size as it did not appear to be a concern (10kb for minified+gzipped is still quite small).

Let me know what you think!

**Comment by bpinto** [comment]
@subzero10 thanks for the reply!

I agree that the package size increase is fine given the size of the package. For context, I noticed the size increase cause we have a GitHub action that will tell us whether a PR is increasing our bundles and by how much. And honestly, I wasn't expecting anything perceptive coming out from the changelog.

> v4.0.5 -> v4.1.0 -> Another big release, but a different kind. We moved to a monorepo for all our javascript packages. With this release, some code from the js package was extracted to a different core package, so I'm surprised to see that the zipped or minified file is actually bigger. However, it may be due to the fact that we now have more typescript .d.ts files generated because we changed the way we build typescript in the projects (we used to use rollup, but now we use the tsc compiler directly to benefit from [Typescript Project References](https://www.typescriptlang.org/docs/handbook/project-references.html)).

I believe types wouldn't affect the final, and minified, javascript file?

I opened up the `honeybadger.min.js` on both [v4.0.5](https://npm-explorer.tk/?p=@honeybadger-io/js@4.0.5/dist/browser/honeybadger.min.js&selection=3:0-3:0) and [v4.1.0](https://npm-explorer.tk/?p=@honeybadger-io/js@4.1.0/dist/browser/honeybadger.min.js&selection=1:0-2:0) and interestingly, I think when migrating to the mono repo it seems like new features were added to the preprocessor.

If you unminify the files, you will see that on v4.1.0 there are differences to handling `globalThis` and also `esModule` references. Seems like there were some, perhaps, bundling changes that could be unnecessary (or not).

I opened the PR to bring attention to this since it's possible that the package now contains support for browsers/environments that it might not need. Feel free to close this issue if there's nothing actionable however. :)

**Comment by subzero10** [comment]
> I believe types wouldn't affect the final, and minified, javascript file?

No they don't (or at least they shouldn't), but they are included in the npm package.

> I opened up the honeybadger.min.js on both [v4.0.5](https://npm-explorer.tk/?p=@honeybadger-io/js@4.0.5/dist/browser/honeybadger.min.js&selection=3:0-3:0) and [v4.1.0](https://npm-explorer.tk/?p=@honeybadger-io/js@4.1.0/dist/browser/honeybadger.min.js&selection=1:0-2:0) and interestingly, I think when migrating to the mono repo it seems like new features were added to the preprocessor.

I didn't know about [npm-explorer.tk](https://npm-explorer.tk), thanks for sharing! With this tool, the unzipped package size of `v4.1.0` is actually smaller than `v4.0.5`, which is expected considering we extracted some code to a different npm package ([@honeybadger-io/core](https://www.npmjs.com/package/@honeybadger-io/core)). However, the zipped package of v4.1.0 is [bigger](https://bundlephobia.com/package/@honeybadger-io/js@4.1.0) 🤷 .
Which part exactly are you referring to with the _preprocessor_ ?

> If you unminify the files, you will see that on v4.1.0 there are differences to handling globalThis and also esModule¹ references. Seems like there were some, perhaps, bundling changes that could be unnecessary (or not).

This is something we already discussed (briefly) with @joshuap and @shalvah, and it's in my todo list to research further on how to improve our bundling for both browser and server.

> I opened the PR to bring attention to this since it's possible that the package now contains support for browsers/environments that it might not need. Feel free to close this issue if there's nothing actionable however. :)

You did very well and we appreciate you taking the time to open the issue! I will go ahead and close the ticket, but as I said above, we plan to work on our bundling.

> I'm thinking about https://github.com/honeybadger-io/honeybadger-js/issues/823, though I'm not familiar with adding support for esModule to a package.

Yeah, there's already a [PR](https://github.com/honeybadger-io/honeybadger-js/pull/828) about this, but integration tests are failing. So I have to dig in a little more (may just end up removing support from older browsers).

**Comment by bpinto** [comment]
> Which part exactly are you referring to with the preprocessor ?

I was talking about rollup.

> You did very well and we appreciate you taking the time to open the issue! I will go ahead and close the ticket, but as I said above, we plan to work on our bundling.

Thanks!
