### ISSUE TITLE
Vite Plugin for Source Maps

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#992]
Is there any documentation / plugin to upload source maps with Vite instead of webpack? I’m unsure how to use the GitHub action with Vite (unsure where source maps are uploaded, the minified url, minified file, etc).

Any help would be appreciated. Using Vue3 + Vite.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_go3tt)

**Comment by subzero10** [comment]
Note:
- It should be under this repo (as a package of the monorepo)
- It should be published on npm with the name `@honeybadger-io/vite-plugin`

**Comment by BethanyBerkowitz** [comment]
@subzero10 I'm tempted to try https://github.com/unjs/unplugin to see if we can get rollup and esbuild as well, and have only one main piece of plugin code. I've never used it before so I'm not sure how easy/difficult it will be to make the existing webpack plugin code work for all these different options. 

If not, I'd still consider building a rollup plugin and then seeing if we can just use it for Vite, since on a first pass through the documentation I think our use case fits their criteria for rollup compatibility: https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility

**Comment by subzero10** [comment]
That's a great idea, @KonnorRogers mentioned `unplugin` about a month ago!

I think you should at least give it a go, probably make it a time-bound exercise if you are concerned that it might be too difficult.

**Comment by BethanyBerkowitz** [comment]
Ok, so I started playing around with `unplugin`... here's where I got to: https://github.com/honeybadger-io/honeybadger-js/compare/BKB/unplugin?expand=1

I started by just trying to re-create the basics of the existing Webpack plugin, along with a small webpack example project using it. The problem I ran into is that our existing Webpack plugin relies on getting the bundle with the file names in it in order to upload the sourcemaps. However, for some reason `unplugin` decided not to pass the args that normally go along with the rollup `writeBundle` hook... I have no idea why. They hook into the timing correctly, but just don't pass the args, so we don't have access to the bundle. 

It should be possible to re-write how we locate the sourcemaps, rather than just getting them directly from the bundle. However, I'm inclined to take a pass at just writing a rollup plugin directly, since unplugin doesn't seem to be as convenient as I expected. 

Very open to suggestions if anyone has a better idea for getting the sourcemap files without the `writeBundle` args though!

**Comment by subzero10** [comment]
I don't have anything to suggest, but you may find useful information here:
- [unplugin-sentry](https://github.com/kricsleo/unplugin-sentry) - unofficial unplugin integration with Sentry
- [Sentry's monorepo for bundler plugins](https://github.com/getsentry/sentry-javascript-bundler-plugins) - based on unplugin. They mention that `writeBundle` does not have all the args, but they claim that Source Map Upload is supported with their package.

In any case, I'm perfectly happy with a vite plugin. In the long-run it might even be easier to maintain. I think the idea of one plugin to support them all might be too good to be true.

**Comment by BethanyBerkowitz** [comment]
@subzero10 Yes, I did read through both of those repos before pivoting away from unplugin last week. Sentry's plugin just calls its CLI library and doesn't actually seem to parse the contents of the bundle like our webpack plugin does. If we were going to follow their lead, I think it would be a major change to how our existing webpack plugin works, so I'm not sure it's worth it. 

In the process of writing a rollup plugin based on the webpack plugin, I'm extracting the functions that I think could easily be shared between the two plugins. So after we have the rollup plugin working, we can move those functions to a shared library.

**Comment by subzero10** [comment]
> So after we have the rollup plugin working, we can move those functions to a shared library.

Sounds good, I like that!
